### ISSUE TITLE
Submission: IIIF Toolkit with Mirador

### ISSUE THREAD

**Issue by dicksonlaw583** [ProjectMirador/mirador-awesome#1]
I would like to add University of Toronto's IIIF Toolkit plugin for Omeka to the list, but there doesn't seem to be a category for this kind of work yet. It doesn't belong under "plugins" because it doesn't plug into Mirador, but it doesn't belong under "implementations" either because it isn't an actual website hosting IIIF content. What's your take on adding this?

Links:

- https://github.com/utlib/IiifItems
- http://omeka.org/add-ons/plugins/iiif-toolkit-with-mirador/

**Comment by snydman** [comment]
Mirador-based tools ?

**Comment by jeffreycwitt** [comment]
Mirador based tools sounds good to me. @dicksonlaw583 Can you just add that section and your two items as a pull request and I'll pull it in.
